# Site settings
title: Harry Baines
description: Portfolio website
url: "harrybaines.net"
baseurl: "https://harrybaines.net"
repo: "https://github.com/harrybaines/harrybaines.github.io"
email: "harryb0905@googlemail.com"
encoding: utf-8
lang: en-GB

# Google Analytics
google_analytics: UA-128207358-1

# Collections
collections:
  pages:
    output: true
    permalink: /:path
  projects:
    output: true
    permalink: /:path

# Permalink style
permalink: pretty

# Site navigation
navigation:
  - title: Projects
    url: /projects.html
  - title: Posts
    url: /posts.html
  - title: About
    url: /about.html

# Files to exclude from Jekyll builds
exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
  - .jekyll-cache
  - .gitignore

# Installed Gems
plugins:
  - jekyll-toc

# Social links
social:
  twitter: https://twitter.com/harryb0905
  github: https://github.com/harrybaines
  kaggle: https://www.kaggle.com/harrybaines
  linkedin: https://www.linkedin.com/in/harry-baines-400609137/

postcss:
  cache: false